"""mig1

Revision ID: 055058cdc577
Revises: 
Create Date: 2025-11-20 05:30:44.155199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055058cdc577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mistake_types',
    sa.Column('id', sa.Integer(), nullable=False, comment='Индентификатор'),
    sa.Column('mistake_type_name', sa.Enum('Шрифт', 'Отступы', 'Структура', 'Подписи иллюстраций', 'Таблицы', 'Ссылки', 'Нумерация', 'Абзацы', 'Заголовки', 'Формулы', 'Списки', 'Колонтитулы', 'Приложения', 'Титульный лист', 'Общий формат', native_enum=False), nullable=False, comment='Наименование типа ошибки'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistake_types')),
    sa.UniqueConstraint('mistake_type_name', name=op.f('uq_mistake_types_mistake_type_name')),
    comment='Типы ошибок'
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False, comment='Индентификатор'),
    sa.Column('status_name', sa.Enum('Загружен', 'Анализируется', 'Проверен', 'Отправлен на доработку', 'Идеален', native_enum=False), nullable=False, comment='Наименование статуса'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses')),
    comment='Статусы'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('first_name', sa.String(), nullable=False, comment='Имя'),
    sa.Column('surname_name', sa.String(), nullable=True, comment='Фамилия'),
    sa.Column('patronomic_name', sa.String(), nullable=True, comment='Отчество'),
    sa.Column('user_name', sa.String(), nullable=False, comment='Логин'),
    sa.Column('password', sa.String(), nullable=False, comment='Пароль'),
    sa.Column('tg_username', sa.String(), nullable=True, comment='Telegram:'),
    sa.Column('is_tg_subscribed', sa.Boolean(), nullable=False, comment='Проверка подписки на Telegram'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Проверка на админа'),
    sa.Column('theme', sa.Enum('dark', 'light', native_enum=False), nullable=False, comment='Тема приложения dark/light'),
    sa.Column('notification_push', sa.Boolean(), nullable=False, comment='Уведомления в браузере on/off'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tg_username', name=op.f('uq_users_tg_username')),
    sa.UniqueConstraint('user_name', name=op.f('uq_users_user_name')),
    comment='Пользователи'
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('file_name', sa.String(), nullable=False, comment='Наименование документа'),
    sa.Column('upload_date', sa.Date(), nullable=False, comment='Дата загрузки'),
    sa.Column('upload_time', sa.Time(), nullable=False, comment='Время загрузки'),
    sa.Column('size', sa.Numeric(precision=5, decimal_return_scale=2), nullable=False, comment='Размер файла'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Связь с User'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='Связь с Status'),
    sa.Column('report_pdf_path', sa.String(), nullable=False, comment='URL на отчет'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Соответсвие ГОСТу'),
    sa.Column('analysis_time', sa.Numeric(precision=5, scale=2), nullable=False, comment='Время анализа'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_documents_status_id_statuses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('file_name', name=op.f('uq_documents_file_name')),
    comment='Документы'
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False, comment='Индентификатор'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Связь с User'),
    sa.Column('mark', sa.Integer(), nullable=False, comment='Оценка от 1 до 5 звезд'),
    sa.Column('review_text', sa.String(), nullable=True, comment='Текст отзыва'),
    sa.Column('created_at', sa.Date(), nullable=False, comment='Время отправки отзыва'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    comment='Отзывы'
    )
    op.create_table('mistakes',
    sa.Column('id', sa.Integer(), nullable=False, comment='Индентификатор'),
    sa.Column('mistake_type_id', sa.Integer(), nullable=True, comment='Связь с Mistake_Type'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание ошибки'),
    sa.Column('critical_status', sa.Enum('Критично', 'Замечание', native_enum=False), nullable=False, comment='Статус важности'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='Связь с Document'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_mistakes_document_id_documents')),
    sa.ForeignKeyConstraint(['mistake_type_id'], ['mistake_types.id'], name=op.f('fk_mistakes_mistake_type_id_mistake_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistakes')),
    comment='Ошибки'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mistakes')
    op.drop_table('reviews')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('statuses')
    op.drop_table('mistake_types')
    # ### end Alembic commands ###
