"""mig5

Revision ID: 958226e45d2d
Revises: 1801e07523ab
Create Date: 2025-11-20 21:34:12.336415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '958226e45d2d'
down_revision = '1801e07523ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable='False',
               existing_comment='Наименование документа')
    op.alter_column('documents', 'upload_date',
               existing_type=sa.DATE(),
               nullable='False',
               existing_comment='Дата загрузки')
    op.alter_column('documents', 'upload_time',
               existing_type=postgresql.TIME(),
               nullable='False',
               existing_comment='Время загрузки')
    op.alter_column('documents', 'size',
               existing_type=sa.NUMERIC(precision=5, scale=0),
               nullable='False',
               existing_comment='Размер файла')
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable='False',
               existing_comment='Связь с User')
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable='False',
               existing_comment='Связь с Status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Связь с Status')
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Связь с User')
    op.alter_column('documents', 'size',
               existing_type=sa.NUMERIC(precision=5, scale=0),
               nullable=True,
               existing_comment='Размер файла')
    op.alter_column('documents', 'upload_time',
               existing_type=postgresql.TIME(),
               nullable=True,
               existing_comment='Время загрузки')
    op.alter_column('documents', 'upload_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='Дата загрузки')
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Наименование документа')
    # ### end Alembic commands ###
