"""empty message

Revision ID: 009e0203f2b5
Revises: e19694ff5d1d
Create Date: 2025-11-23 00:16:52.861753

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '009e0203f2b5'
down_revision = 'e19694ff5d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mistake_types',
    sa.Column('mistake_type_id', sa.Integer(), nullable=False, comment='Индентификатор'),
    sa.Column('mistake_type_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('mistake_type_id'),
    sa.UniqueConstraint('mistake_type_name'),
    schema='my_app_schema',
    comment='Типы ошибок'
    )
    op.create_table('statuses',
    sa.Column('status_id', sa.Integer(), nullable=False, comment='Индентификатор'),
    sa.Column('status_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    schema='my_app_schema',
    comment='Статусы'
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False, comment='Индентификатор'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Связь с User'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Оценка от 1 до 5 звезд'),
    sa.Column('review_text', sa.Text(), nullable=True, comment='Текст отзыва'),
    sa.Column('created_at', sa.Date(), nullable=False, comment='Время отправки отзыва'),
    sa.ForeignKeyConstraint(['user_id'], ['my_app_schema.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id'),
    schema='my_app_schema',
    comment='Отзывы'
    )
    op.create_table('mistakes',
    sa.Column('mistake_id', sa.Integer(), nullable=False, comment='Индентификатор'),
    sa.Column('mistake_type_id', sa.Integer(), nullable=True, comment='Связь с Mistake_Type'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание ошибки'),
    sa.Column('critical_status', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='Связь с Document'),
    sa.ForeignKeyConstraint(['document_id'], ['my_app_schema.documents.document_id'], ),
    sa.ForeignKeyConstraint(['mistake_type_id'], ['my_app_schema.mistake_types.mistake_type_id'], ),
    sa.PrimaryKeyConstraint('mistake_id'),
    schema='my_app_schema',
    comment='Ошибки'
    )
    op.add_column('documents', sa.Column('filename', sa.String(), nullable=False), schema='my_app_schema')
    op.add_column('documents', sa.Column('filepath', sa.String(), nullable=False), schema='my_app_schema')
    op.add_column('documents', sa.Column('upload_datetime', sa.DateTime(), nullable=False, comment='Дата и время загрузки'), schema='my_app_schema')
    op.add_column('documents', sa.Column('size', sa.Numeric(precision=10, scale=2), nullable=False), schema='my_app_schema')
    op.add_column('documents', sa.Column('status_id', sa.Integer(), nullable=False), schema='my_app_schema')
    op.add_column('documents', sa.Column('report_pdf_path', sa.String(length=500), nullable=False), schema='my_app_schema')
    op.add_column('documents', sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Соответствие стандарту (0-100)'), schema='my_app_schema')
    op.add_column('documents', sa.Column('analysis_time', sa.Numeric(precision=7, scale=2), nullable=False), schema='my_app_schema')
    op.create_unique_constraint(None, 'documents', ['filename'], schema='my_app_schema')
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', schema='my_app_schema', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['user_id'], source_schema='my_app_schema', referent_schema='my_app_schema', ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'statuses', ['status_id'], ['status_id'], source_schema='my_app_schema', referent_schema='my_app_schema')
    op.create_table_comment(
        'documents',
        'Документы',
        existing_comment=None,
        schema='my_app_schema'
    )
    op.drop_column('documents', 'file_name', schema='my_app_schema')
    op.drop_column('documents', 'file_path', schema='my_app_schema')
    op.drop_column('documents', 'uploaded_at', schema='my_app_schema')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False, comment='Логин'), schema='my_app_schema')
    op.add_column('users', sa.Column('tg_username', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True, comment='Telegram:'), schema='my_app_schema')
    op.add_column('users', sa.Column('is_tg_subscribed', sa.Boolean(), nullable=False), schema='my_app_schema')
    op.add_column('users', sa.Column('theme', sa.String(length=10), nullable=False), schema='my_app_schema')
    op.add_column('users', sa.Column('is_push_enabled', sa.Boolean(), nullable=False), schema='my_app_schema')
    op.drop_constraint(op.f('users_user_name_key'), 'users', schema='my_app_schema', type_='unique')
    op.create_unique_constraint(None, 'users', ['tg_username'], schema='my_app_schema')
    op.create_unique_constraint(None, 'users', ['username'], schema='my_app_schema')
    op.drop_column('users', 'user_name', schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Логин'), schema='my_app_schema')
    op.drop_constraint(None, 'users', schema='my_app_schema', type_='unique')
    op.drop_constraint(None, 'users', schema='my_app_schema', type_='unique')
    op.create_unique_constraint(op.f('users_user_name_key'), 'users', ['user_name'], schema='my_app_schema')
    op.drop_column('users', 'is_push_enabled', schema='my_app_schema')
    op.drop_column('users', 'theme', schema='my_app_schema')
    op.drop_column('users', 'is_tg_subscribed', schema='my_app_schema')
    op.drop_column('users', 'tg_username', schema='my_app_schema')
    op.drop_column('users', 'username', schema='my_app_schema')
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='my_app_schema')
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False), schema='my_app_schema')
    op.add_column('documents', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False), schema='my_app_schema')
    op.drop_table_comment(
        'documents',
        existing_comment='Документы',
        schema='my_app_schema'
    )
    op.drop_constraint(None, 'documents', schema='my_app_schema', type_='foreignkey')
    op.drop_constraint(None, 'documents', schema='my_app_schema', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['user_id'], source_schema='my_app_schema', referent_schema='my_app_schema')
    op.drop_constraint(None, 'documents', schema='my_app_schema', type_='unique')
    op.drop_column('documents', 'analysis_time', schema='my_app_schema')
    op.drop_column('documents', 'score', schema='my_app_schema')
    op.drop_column('documents', 'report_pdf_path', schema='my_app_schema')
    op.drop_column('documents', 'status_id', schema='my_app_schema')
    op.drop_column('documents', 'size', schema='my_app_schema')
    op.drop_column('documents', 'upload_datetime', schema='my_app_schema')
    op.drop_column('documents', 'filepath', schema='my_app_schema')
    op.drop_column('documents', 'filename', schema='my_app_schema')
    op.drop_table('mistakes', schema='my_app_schema')
    op.drop_table('reviews', schema='my_app_schema')
    op.drop_table('statuses', schema='my_app_schema')
    op.drop_table('mistake_types', schema='my_app_schema')
    # ### end Alembic commands ###
