"""empty message

Revision ID: 1cbbecfe42a9
Revises: 67fc630015da
Create Date: 2025-12-01 19:46:01.002315

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '1cbbecfe42a9'
down_revision = '67fc630015da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
