"""empty message

Revision ID: 31acd4db1825
Revises: 
Create Date: 2025-10-16 23:02:30.103648

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '31acd4db1825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standart',
    sa.Column('standart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('standart_id'),
    schema='my_app_schema'
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='my_app_schema'
    )
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('is_example', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['my_app_schema.users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id'),
    schema='my_app_schema'
    )
    op.create_table('check',
    sa.Column('check_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('standart_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['my_app_schema.documents.document_id'], ),
    sa.ForeignKeyConstraint(['standart_id'], ['my_app_schema.standart.standart_id'], ),
    sa.PrimaryKeyConstraint('check_id'),
    schema='my_app_schema'
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['my_app_schema.check.check_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    schema='my_app_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports', schema='my_app_schema')
    op.drop_table('check', schema='my_app_schema')
    op.drop_table('documents', schema='my_app_schema')
    op.drop_table('users', schema='my_app_schema')
    op.drop_table('standart', schema='my_app_schema')
    # ### end Alembic commands ###
