"""empty message

Revision ID: 67fc630015da
Revises: 009e0203f2b5
Create Date: 2025-11-28 18:07:55.208846

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '67fc630015da'
down_revision = '009e0203f2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mistakes', 'mistake_type_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Связь с Mistake_Type',
               existing_nullable=True,
               schema='my_app_schema')
    op.alter_column('mistakes', 'document_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Связь с Document',
               existing_nullable=False,
               schema='my_app_schema')
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Связь с User',
               existing_nullable=False,
               schema='my_app_schema')
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True, comment='Telegram user ID (числовой)'), schema='my_app_schema')
    op.create_unique_constraint(None, 'users', ['telegram_id'], schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='my_app_schema', type_='unique')
    op.drop_column('users', 'telegram_id', schema='my_app_schema')
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Связь с User',
               existing_nullable=False,
               schema='my_app_schema')
    op.alter_column('mistakes', 'document_id',
               existing_type=sa.INTEGER(),
               comment='Связь с Document',
               existing_nullable=False,
               schema='my_app_schema')
    op.alter_column('mistakes', 'mistake_type_id',
               existing_type=sa.INTEGER(),
               comment='Связь с Mistake_Type',
               existing_nullable=True,
               schema='my_app_schema')
    # ### end Alembic commands ###
