"""empty message

Revision ID: 6a663012f295
Revises: f036b050fd6c
Create Date: 2026-04-22 17:48:21.057090

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '6a663012f295'
down_revision = 'f036b050fd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_data', sa.Text(), nullable=True, comment='Аватарка в base64'), schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_data', schema='my_app_schema')
    # ### end Alembic commands ###
