"""empty message

Revision ID: 762ca29551c6
Revises: 31acd4db1825
Create Date: 2025-11-10 20:55:11.824598

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '762ca29551c6'
down_revision = '31acd4db1825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin', schema='my_app_schema')
    # ### end Alembic commands ###
