"""Change score to integer

Revision ID: 7eae78c62426
Revises: a09a0b727e23
Create Date: 2026-02-17 01:49:58.659931

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '7eae78c62426'
down_revision = 'a09a0b727e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               existing_comment='Соответствие стандарту (0-100)',
               existing_nullable=False,
               schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'score',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_comment='Соответствие стандарту (0-100)',
               existing_nullable=False,
               schema='my_app_schema')
    # ### end Alembic commands ###
