"""empty message

Revision ID: a09a0b727e23
Revises: 1cbbecfe42a9
Create Date: 2026-02-05 01:23:50.847967

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'a09a0b727e23'
down_revision = '1cbbecfe42a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('score', sa.Integer(), nullable=True), schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check', 'score', schema='my_app_schema')
    # ### end Alembic commands ###
