"""empty message

Revision ID: e19694ff5d1d
Revises: fac14221b08c
Create Date: 2025-11-14 23:06:11.094462

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'e19694ff5d1d'
down_revision = 'fac14221b08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
