"""empty message

Revision ID: f036b050fd6c
Revises: 7eae78c62426
Create Date: 2026-04-19 00:33:05.070164

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'f036b050fd6c'
down_revision = '7eae78c62426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standart', sa.Column('rules_file', sa.String(length=512), nullable=True), schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standart', 'rules_file', schema='my_app_schema')
    # ### end Alembic commands ###
