"""empty message

Revision ID: fac14221b08c
Revises: 762ca29551c6
Create Date: 2025-11-14 23:03:08.912949

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'fac14221b08c'
down_revision = '762ca29551c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False, comment='Имя'), schema='my_app_schema')
    op.add_column('users', sa.Column('surname_name', sa.String(), nullable=False, comment='Фамилия'), schema='my_app_schema')
    op.add_column('users', sa.Column('patronomic_name', sa.String(), nullable=False, comment='Отчество'), schema='my_app_schema')
    op.add_column('users', sa.Column('user_name', sa.String(), nullable=False, comment='Логин'), schema='my_app_schema')
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('my_app_schema.users_user_id_seq'::regclass)"),
               schema='my_app_schema')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='Почта',
               existing_nullable=False,
               schema='my_app_schema')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               comment='Пароль',
               existing_nullable=False,
               schema='my_app_schema')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               comment='Роль',
               existing_nullable=False,
               schema='my_app_schema')
    op.create_unique_constraint(None, 'users', ['user_name'], schema='my_app_schema')
    op.create_table_comment(
        'users',
        'Пользователи',
        existing_comment=None,
        schema='my_app_schema'
    )
    op.drop_column('users', 'name', schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False), schema='my_app_schema')
    op.drop_table_comment(
        'users',
        existing_comment='Пользователи',
        schema='my_app_schema'
    )
    op.drop_constraint(None, 'users', schema='my_app_schema', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Роль',
               existing_nullable=False,
               schema='my_app_schema')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Пароль',
               existing_nullable=False,
               schema='my_app_schema')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Почта',
               existing_nullable=False,
               schema='my_app_schema')
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('my_app_schema.users_user_id_seq'::regclass)"),
               schema='my_app_schema')
    op.drop_column('users', 'user_name', schema='my_app_schema')
    op.drop_column('users', 'patronomic_name', schema='my_app_schema')
    op.drop_column('users', 'surname_name', schema='my_app_schema')
    op.drop_column('users', 'first_name', schema='my_app_schema')
    # ### end Alembic commands ###
